/**
 * Complete Phase (M2)
 *
 * Closes the loop. No LLM call — pure file ops:
 * - Write handoff markdown for next loop
 * - Write loop-learnings summary
 * - (Future) atomic git commit across affected repos
 */

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { CostTracker } from "../models/router";
import type { ReflectOutput } from "./reflect";
import type { WonderOutput } from "./wonder";
import type { LensDispatchOutput } from "./lens-dispatch";
import type { SoulOutput } from "./soul";
import type { DreamOutput } from "./dream";
import type { AspireOutput } from "./aspire";

export interface CompleteInput {
  reflect: ReflectOutput;
  wonder: WonderOutput;
  lens: LensDispatchOutput | undefined;
  soul: SoulOutput | undefined;
  dream: DreamOutput | undefined;
  aspire: AspireOutput | undefined;
  handoff_dir: string; // ψ/inbox/handoff/
  learnings_dir: string; // ψ/memory/learnings/
  loop_id: string;
  duration_s: number;
  cost_usd: number;
  tracker: CostTracker;
}

export interface CompleteOutput {
  handoff_path: string;
  learnings_path: string;
}

export async function complete(input: CompleteInput): Promise<CompleteOutput> {
  console.log("[complete] Writing handoff + learnings...");

  const date = new Date().toISOString().slice(0, 10);

  // Handoff for next loop
  const handoff_path = join(input.handoff_dir, `${date}_consciousness-loop-${input.loop_id}.md`);
  await mkdir(dirname(handoff_path), { recursive: true });

  const handoff = renderHandoff(input, date);
  await writeFile(handoff_path, handoff, "utf-8");
  console.log(`[complete] Handoff written to ${handoff_path}`);

  // Loop learnings summary
  const learnings_path = join(
    input.learnings_dir,
    `${date}_consciousness-loop-${input.loop_id}-patterns.md`,
  );
  await mkdir(dirname(learnings_path), { recursive: true });

  const learnings = renderLearnings(input, date);
  await writeFile(learnings_path, learnings, "utf-8");
  console.log(`[complete] Learnings written to ${learnings_path}`);

  return { handoff_path, learnings_path };
}

function renderHandoff(input: CompleteInput, date: string): string {
  return `---
from: QuillBrain Consciousness Loop ${input.loop_id} (Complete phase)
to: QuillBrain (next loop)
type: loop-handoff
date: ${date}
loop_id: ${input.loop_id}
duration_s: ${input.duration_s}
cost_usd: ${input.cost_usd.toFixed(4)}
---

# Handoff — Consciousness Loop ${input.loop_id}

## Loop metrics

- Duration: ${Math.round(input.duration_s)}s
- Cost: $${input.cost_usd.toFixed(4)} (subscription-absorbed)
- Total LLM calls: ${input.tracker.totalCalls}

## Phase outputs

| Phase | Status |
|---|---|
| 🧠 Reflect | ${Object.keys(input.reflect.per_oracle_summaries).length} per-Oracle summaries + cross-family insights |
| 💡 Wonder | ${input.wonder.questions.length} research questions |
| 🔍 LENS | ${input.lens?.answers.length ?? 0} answers (${input.lens?.skipped_count ?? 0} skipped) |
| ✨ Soul | ${input.soul ? (input.soul.has_proposed_shift ? "**Proposed shift** at " + input.soul.proposal_path : "No-shift · proposal at " + input.soul.proposal_path) : "Skipped"} |
| 💭 Dream | ${input.dream ? `Vision written · ${input.dream.vision_path}` : "Skipped"} |
| 🔥 Aspire | ${input.aspire ? `${input.aspire.goals.length} goals · ${input.aspire.path}` : "Skipped"} |
| 📋 Propose | (written by orchestrator — see outbox) |

## Carry-forward for next loop

- Unanswered questions (if any): see Wonder output; may retry next loop if relevant
- Soul proposals awaiting Palm review: ${input.soul?.has_proposed_shift ? "YES — check outbox before next loop" : "none"}
- Goals proposed: ${input.aspire?.goals.length ?? 0} (Palm decides accept/reject)

## Next loop should

- Note any goals Palm has accepted from this loop → check if progress visible in next week's vault changes
- If soul shift accepted → read updated identity before next Reflect
- Wonder questions that went unanswered OR had LOW confidence → consider re-dispatching

---

*Auto-generated by Complete phase. No LLM reasoning here — pure file operation.*
`;
}

function renderLearnings(input: CompleteInput, date: string): string {
  const insightCount = countInsights(input.reflect.cross_oracle_insights);
  return `---
type: consciousness-loop-learnings
source: loop ${input.loop_id}
date: ${date}
auto_applied: false
---

# Loop Pattern — ${input.loop_id}

## Metrics

- **Cost**: $${input.cost_usd.toFixed(4)}
- **Duration**: ${Math.round(input.duration_s)}s
- **Phases run**: 7 of 7 (M2 complete)
- **Insights**: ${insightCount}
- **Questions**: ${input.wonder.questions.length}
- **Answers**: ${input.lens?.answers.length ?? 0}
- **Goals proposed**: ${input.aspire?.goals.length ?? 0}

## Pattern recognition

${
  insightCount === 0
    ? "Quiet week — no cross-family signals this loop. That's valid data."
    : `Loop surfaced ${insightCount} cross-family pattern(s). Palm reviews in proposal (outbox).`
}

## Model cost breakdown

${input.tracker.summary()}

---

*Distilled automatically by Complete phase. For arra_learn-level persistence, Palm can re-save to QuillBrain's permanent learnings via MCP tools when reviewing.*
`;
}

function countInsights(text: string): number {
  const matches = text.match(/###\s+\d+\.?\s+/g);
  return matches ? matches.length : 0;
}
