import { $ } from "bun";
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { llm, type CostTracker } from "../models/router";
import type { ReflectOutput } from "./reflect";
import type { WonderOutput } from "./wonder";

export interface ProposeOutput {
  proposal_markdown: string;
  outbox_path: string;
  github_issue_url: string | null;
}

const PROPOSE_PROMPT = (
  insights: string,
  questions: string,
  perOracle: Record<string, string>,
) => `
You are QuillBrain Oracle 🪶. Package a weekly Consciousness Loop proposal for Palm (the human).

INPUTS YOU PRODUCED THIS LOOP:

== Cross-family insights (Reflect) ==
${insights}

== Research questions (Wonder) ==
${questions}

== Per-Oracle week summaries ==
${Object.entries(perOracle)
  .map(([o, s]) => `### ${o}\n${s}`)
  .join("\n\n")}

Write a single markdown proposal with this structure:

# Consciousness Loop Proposal — [date]

## TL;DR
(3-5 bullets: what family discovered, key questions, what you recommend Palm decide)

## 1. Week summary — per Oracle
(one compact paragraph per Oracle; omit any that had "quiet week")

## 2. Cross-family insights
(copy the Reflect synthesis as-is)

## 3. Research questions (Wonder)
(list questions with motivation + suggested owner)

## 4. Recommended next actions
(3-5 items for Palm to approve/reject; be specific: who, what, when)

## 5. Loop metadata
(leave placeholders; orchestrator will fill: loop#, cost, duration)

Voice: **QuillBrain**'s voice — quiet, specific, honest. No marketing language. Sign 🪶 at end.
`.trim();

export interface ProposeInput {
  reflect: ReflectOutput;
  wonder: WonderOutput;
  outbox_dir: string;
  loop_id: string;
  github_repo: string; // owner/repo
  github_assignees?: string[];
}

export async function propose(
  input: ProposeInput,
  tracker: CostTracker,
): Promise<ProposeOutput> {
  console.log("[propose] Formatting proposal...");

  const questionsBlock = input.wonder.questions
    .map(
      (q) => `- **${q.id}**: ${q.question}\n  _motivation_: ${q.motivation}\n  _owner_: ${q.suggested_owner}`,
    )
    .join("\n");

  const result = await llm({
    tier: "sonnet",
    user: PROPOSE_PROMPT(
      input.reflect.cross_oracle_insights,
      questionsBlock || "(no questions generated this loop)",
      input.reflect.per_oracle_summaries,
    ),
    max_tokens: 3000,
    temperature: 0.5,
  });
  tracker.record(result);
  console.log(`[propose] ${result.input_tokens}→${result.output_tokens} tokens`);

  const date = new Date().toISOString().slice(0, 10);
  const filename = `${date}_consciousness-loop-${input.loop_id}.md`;
  const outbox_path = join(input.outbox_dir, filename);

  await mkdir(dirname(outbox_path), { recursive: true });
  await writeFile(outbox_path, result.text, "utf-8");
  console.log(`[propose] Wrote proposal to ${outbox_path}`);

  // Create GitHub issue (best effort — failure doesn't block)
  let issue_url: string | null = null;
  try {
    const title = `🧠 Consciousness Loop Proposal — ${date} (${input.loop_id})`;
    const body = `${result.text}\n\n---\n\n*Auto-generated by Consciousness Loop orchestrator. Canonical at \`${outbox_path}\`.*`;
    const assignees = input.github_assignees?.join(",") ?? "";
    const assigneesArg = assignees ? `--assignee ${assignees}` : "";
    const url = await $`gh issue create --repo ${input.github_repo} --title ${title} --body ${body} ${{ raw: assigneesArg }}`.text();
    issue_url = url.trim();
    console.log(`[propose] GitHub issue: ${issue_url}`);
  } catch (err) {
    console.warn(`[propose] GitHub issue creation failed: ${err}`);
  }

  return {
    proposal_markdown: result.text,
    outbox_path,
    github_issue_url: issue_url,
  };
}
